name: CI/CD Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt || echo "requirements.txt missing or invalid"
          pip install pytest Flask  # Ensure required packages

      - name: Start Backend Server
        run: |
          python backend/app.py > backend.log 2>&1 &  # Run Flask app in background
          sleep 10  # Give it time to start

      - name: Check if Backend is Running
        run: |
          sleep 10
          curl -I http://127.0.0.1:5000 || (echo "Backend did not start" && cat backend.log && exit 1)

      - name: Run Unit Tests
        run: |
          pytest tests/  # Run all test files in tests/

      - name: Run Pylint
        run: |
          pylint --rcfile=.pylintrc $(git ls-files '*.py')  # Lint all Python files
