name: CI/CD Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest  # Ensure pytest is installed

      - name: Start Backend Server
        run: |
          python backend/app.py &  # Run Flask app in the background
          sleep 5  # Give it time to start

      - name: Run Unit Tests
        run: |
          pytest tests/  # Run all test files in tests/

      - name: Run Pylint
        run: |
          pylint --rcfile=.pylintrc $(git ls-files '*.py')  # Lint all Python files
