name: CI/CD Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt || echo "requirements.txt missing or invalid"
          pip install pytest Flask
          pip install pylint

      - name: Start Backend Server
        run: |
          python backend/app.py > backend.log 2>&1 &  # Run Flask app in background
          sleep 10  

      - name: Check if Backend is Running
        run: |
          sleep 10
          if curl -I http://127.0.0.1:5000; then
            echo "Backend is running."
            echo "RUN_TESTS=true" >> $GITHUB_ENV
          else
            echo "Backend failed to start, skipping tests."
            echo "RUN_TESTS=false" >> $GITHUB_ENV
            cat backend.log  # Print backend logs for debugging
          fi

      - name: Run Unit Tests (If Backend is Running)
        if: env.RUN_TESTS == 'true'
        run: |
          pytest tests/

      - name: Run Pylint
        run: |
          pylint --rcfile=.pylintrc $(git ls-files '*.py')  # Lint all Python files
